import type { Metadata } from "next";
import { Poppins,Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { Toaster } from 'react-hot-toast';
import { Montserrat } from 'next/font/google';
import Sidebar from "@/components/sidebar";

const font=Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choisis ce que tu veux
  variable: '--font-poppins',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fare Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.variable} suppressHydrationWarning>
        <head />
        <body className=" text-black text-[18px] bg-gray-200 dark:bg-gray-800">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster position="top-left" reverseOrder={false} />
          </ThemeProvider>
        </body>
    </html>
  );
}
